name: Mirror to AWS CodeCommit Repository

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: guilhermebresser/github-mirror@latest
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:guilhermebresser/git-mirror-action.git'
          destination-repo: 'git-codecommit.us-east-1.amazonaws.com/v1/repos/teste'
